listen_addresses = '*'
port = 5432
max_connections = 40
shared_buffers = 96MB
effective_cache_size = 256MB
work_mem = 2MB
maintenance_work_mem = 32MB
wal_buffers = 4MB
max_wal_size = 512MB
min_wal_size = 80MB
log_destination = 'stderr'
logging_collector = off
log_statement = 'none'
log_min_duration_statement = 1000
