"""create Phase 1 scheduling tables

Revision ID: ffc99a7e1d4f
Revises:
Create Date: 2026-08-17 22:00:02.897845
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "ffc99a7e1d4f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedules",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("creator_user_id", sa.BigInteger(), nullable=False),
        sa.Column("schedule_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("content", sa.String(length=2000), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("local_time", sa.Time(), nullable=True),
        sa.Column("weekday", sa.SmallInteger(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(schedule_type = 'once' AND local_time IS NULL AND weekday IS NULL) OR (schedule_type = 'daily' AND local_time IS NOT NULL AND weekday IS NULL) OR (schedule_type = 'weekly' AND local_time IS NOT NULL AND weekday IS NOT NULL)",
            name=op.f("ck_schedules_recurrence_fields_valid"),
        ),
        sa.CheckConstraint(
            "(status = 'deleted' AND deleted_at IS NOT NULL) OR (status <> 'deleted' AND deleted_at IS NULL)",
            name=op.f("ck_schedules_deleted_at_matches_status"),
        ),
        sa.CheckConstraint(
            "(status = 'draft' AND content IS NULL) OR status IN ('paused', 'deleted') OR (status IN ('active', 'failed', 'completed', 'ended') AND content IS NOT NULL)",
            name=op.f("ck_schedules_content_matches_status"),
        ),
        sa.CheckConstraint(
            "(status IN ('completed', 'ended', 'deleted') AND terminal_at IS NOT NULL) OR (status NOT IN ('completed', 'ended', 'deleted') AND terminal_at IS NULL)",
            name=op.f("ck_schedules_terminal_at_matches_status"),
        ),
        sa.CheckConstraint(
            "(status IN ('completed', 'failed') AND schedule_type = 'once') OR (status IN ('paused', 'ended') AND schedule_type IN ('daily', 'weekly')) OR status IN ('draft', 'active', 'deleted')",
            name=op.f("ck_schedules_status_matches_schedule_type"),
        ),
        sa.CheckConstraint(
            "(status IN ('draft', 'active') AND next_run_at IS NOT NULL) OR (status IN ('paused', 'failed', 'completed', 'ended', 'deleted') AND next_run_at IS NULL)",
            name=op.f("ck_schedules_next_run_matches_status"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR schedule_type IN ('daily', 'weekly')",
            name=op.f("ck_schedules_end_date_recurring_only"),
        ),
        sa.CheckConstraint(
            "schedule_type IN ('once', 'daily', 'weekly')",
            name=op.f("ck_schedules_schedule_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'paused', 'failed', 'completed', 'ended', 'deleted')",
            name=op.f("ck_schedules_status_valid"),
        ),
        sa.CheckConstraint("channel_id > 0", name=op.f("ck_schedules_channel_id_positive")),
        sa.CheckConstraint(
            "content IS NULL OR char_length(content) BETWEEN 1 AND 2000",
            name=op.f("ck_schedules_content_length_valid"),
        ),
        sa.CheckConstraint(
            "creator_user_id > 0", name=op.f("ck_schedules_creator_user_id_positive")
        ),
        sa.CheckConstraint("guild_id > 0", name=op.f("ck_schedules_guild_id_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_schedules_version_positive")),
        sa.CheckConstraint(
            "weekday IS NULL OR weekday BETWEEN 0 AND 6", name=op.f("ck_schedules_weekday_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
        sa.UniqueConstraint("public_id", name=op.f("uq_schedules_public_id")),
    )
    op.create_index(
        "ix_schedules_creator_status_next_run",
        "schedules",
        ["creator_user_id", "status", "next_run_at"],
        unique=False,
    )
    op.create_index(
        "ix_schedules_guild_status_next_run",
        "schedules",
        ["guild_id", "status", "next_run_at"],
        unique=False,
    )
    op.create_index(
        "ix_schedules_status_terminal_at", "schedules", ["status", "terminal_at"], unique=False
    )
    op.create_table(
        "operation_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("schedule_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("delete_kind", sa.String(length=32), nullable=True),
        sa.Column("delete_reason", sa.String(length=500), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(action = 'deleted' AND delete_kind IS NOT NULL AND delete_reason IS NOT NULL AND char_length(delete_reason) BETWEEN 1 AND 500) OR (action <> 'deleted' AND delete_kind IS NULL AND delete_reason IS NULL)",
            name=op.f("ck_operation_logs_delete_fields_match_action"),
        ),
        sa.CheckConstraint(
            "(actor_type = 'user' AND actor_user_id IS NOT NULL) OR (actor_type = 'system' AND actor_user_id IS NULL)",
            name=op.f("ck_operation_logs_actor_user_matches_type"),
        ),
        sa.CheckConstraint(
            "action IN ('created', 'edited', 'deleted', 'paused', 'resumed', 'ended', 'failed')",
            name=op.f("ck_operation_logs_action_valid"),
        ),
        sa.CheckConstraint(
            "actor_type IN ('user', 'system')", name=op.f("ck_operation_logs_actor_type_valid")
        ),
        sa.CheckConstraint(
            "delete_kind IS NULL OR delete_kind IN ('creator_deleted', 'admin_deleted', 'operator_resolved_failed')",
            name=op.f("ck_operation_logs_delete_kind_valid"),
        ),
        sa.CheckConstraint(
            "actor_user_id IS NULL OR actor_user_id > 0",
            name=op.f("ck_operation_logs_actor_user_id_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_operation_logs_schedule_id_schedules"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_logs")),
    )
    op.create_index(
        "ix_operation_logs_actor_created_desc",
        "operation_logs",
        ["actor_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_operation_logs_schedule_created_desc",
        "operation_logs",
        ["schedule_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "schedule_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("schedule_id", sa.BigInteger(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.UUID(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discord_message_id", sa.BigInteger(), nullable=True),
        sa.Column("result_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'pending' AND next_attempt_at IS NOT NULL) OR (status <> 'pending' AND next_attempt_at IS NULL)",
            name=op.f("ck_schedule_runs_next_attempt_matches_status"),
        ),
        sa.CheckConstraint(
            "(status = 'succeeded' AND discord_message_id IS NOT NULL) OR (status <> 'succeeded' AND discord_message_id IS NULL)",
            name=op.f("ck_schedule_runs_message_id_matches_status"),
        ),
        sa.CheckConstraint(
            "(status IN ('succeeded', 'failed', 'skipped') AND finished_at IS NOT NULL) OR (status IN ('pending', 'processing') AND finished_at IS NULL)",
            name=op.f("ck_schedule_runs_finished_at_matches_status"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'succeeded', 'failed', 'skipped')",
            name=op.f("ck_schedule_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "attempt_count BETWEEN 0 AND 4", name=op.f("ck_schedule_runs_attempt_count_valid")
        ),
        sa.CheckConstraint(
            "discord_message_id IS NULL OR discord_message_id > 0",
            name=op.f("ck_schedule_runs_message_id_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_schedule_runs_schedule_id_schedules"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_runs")),
        sa.UniqueConstraint(
            "schedule_id", "scheduled_for", name=op.f("uq_schedule_runs_schedule_id_scheduled_for")
        ),
    )
    op.create_index(
        "ix_schedule_runs_pending_due",
        "schedule_runs",
        ["next_attempt_at", "scheduled_for"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_schedule_runs_processing_lease",
        "schedule_runs",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'processing'"),
    )
    op.create_index(
        "ix_schedule_runs_schedule_scheduled_desc",
        "schedule_runs",
        ["schedule_id", sa.literal_column("scheduled_for DESC")],
        unique=False,
    )
    op.create_index(
        "ix_schedule_runs_status_finished_at",
        "schedule_runs",
        ["status", "finished_at"],
        unique=False,
    )
    op.create_table(
        "delivery_attempts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("schedule_run_id", sa.BigInteger(), nullable=False),
        sa.Column("attempt_number", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("claimed_by", sa.UUID(), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("send_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discord_message_id", sa.BigInteger(), nullable=True),
        sa.Column("error_kind", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "(status = 'succeeded' AND discord_message_id IS NOT NULL) OR (status <> 'succeeded' AND discord_message_id IS NULL)",
            name=op.f("ck_delivery_attempts_message_id_matches_status"),
        ),
        sa.CheckConstraint(
            "(status IN ('sending', 'succeeded', 'unknown') AND send_started_at IS NOT NULL) OR (status = 'claimed' AND send_started_at IS NULL) OR status = 'failed'",
            name=op.f("ck_delivery_attempts_send_started_at_matches_status"),
        ),
        sa.CheckConstraint(
            "(status IN ('succeeded', 'failed', 'unknown') AND finished_at IS NOT NULL) OR (status IN ('claimed', 'sending') AND finished_at IS NULL)",
            name=op.f("ck_delivery_attempts_finished_at_matches_status"),
        ),
        sa.CheckConstraint(
            "error_kind IS NULL OR error_kind IN ('transient', 'permanent', 'unknown')",
            name=op.f("ck_delivery_attempts_error_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('claimed', 'sending', 'succeeded', 'failed', 'unknown')",
            name=op.f("ck_delivery_attempts_status_valid"),
        ),
        sa.CheckConstraint(
            "attempt_number BETWEEN 1 AND 4", name=op.f("ck_delivery_attempts_attempt_number_valid")
        ),
        sa.CheckConstraint(
            "discord_message_id IS NULL OR discord_message_id > 0",
            name=op.f("ck_delivery_attempts_message_id_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["schedule_run_id"],
            ["schedule_runs.id"],
            name=op.f("fk_delivery_attempts_schedule_run_id_schedule_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_attempts")),
        sa.UniqueConstraint(
            "schedule_run_id",
            "attempt_number",
            name=op.f("uq_delivery_attempts_schedule_run_id_attempt_number"),
        ),
    )
    op.create_index(
        "ix_delivery_attempts_status_claimed_at",
        "delivery_attempts",
        ["status", "claimed_at"],
        unique=False,
    )
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("schedule_id", sa.BigInteger(), nullable=True),
        sa.Column("schedule_run_id", sa.BigInteger(), nullable=True),
        sa.Column("notification_type", sa.String(length=32), nullable=False),
        sa.Column("recipient_type", sa.String(length=32), nullable=False),
        sa.Column("recipient_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("deduplication_key", sa.String(length=160), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(recipient_type = 'log' AND recipient_id IS NULL) OR (recipient_type <> 'log' AND recipient_id IS NOT NULL)",
            name=op.f("ck_notification_logs_recipient_id_matches_type"),
        ),
        sa.CheckConstraint(
            "(status = 'succeeded' AND sent_at IS NOT NULL) OR (status <> 'succeeded' AND sent_at IS NULL)",
            name=op.f("ck_notification_logs_sent_at_matches_status"),
        ),
        sa.CheckConstraint(
            "notification_type IN ('draft_24h', 'draft_1h', 'draft_immediate', 'run_failed', 'run_delayed', 'run_skipped', 'recovery')",
            name=op.f("ck_notification_logs_notification_type_valid"),
        ),
        sa.CheckConstraint(
            "recipient_type IN ('creator_dm', 'operator_channel', 'operator_dm', 'log')",
            name=op.f("ck_notification_logs_recipient_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'succeeded', 'failed')",
            name=op.f("ck_notification_logs_status_valid"),
        ),
        sa.CheckConstraint(
            "recipient_id IS NULL OR recipient_id > 0",
            name=op.f("ck_notification_logs_recipient_id_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_notification_logs_schedule_id_schedules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_run_id"],
            ["schedule_runs.id"],
            name=op.f("fk_notification_logs_schedule_run_id_schedule_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_logs")),
        sa.UniqueConstraint(
            "deduplication_key", name=op.f("uq_notification_logs_deduplication_key")
        ),
    )
    op.create_index(
        "ix_notification_logs_schedule_created_desc",
        "notification_logs",
        ["schedule_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_notification_logs_status_created_at",
        "notification_logs",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_logs_status_created_at", table_name="notification_logs")
    op.drop_index("ix_notification_logs_schedule_created_desc", table_name="notification_logs")
    op.drop_table("notification_logs")
    op.drop_index("ix_delivery_attempts_status_claimed_at", table_name="delivery_attempts")
    op.drop_table("delivery_attempts")
    op.drop_index("ix_schedule_runs_status_finished_at", table_name="schedule_runs")
    op.drop_index("ix_schedule_runs_schedule_scheduled_desc", table_name="schedule_runs")
    op.drop_index(
        "ix_schedule_runs_processing_lease",
        table_name="schedule_runs",
        postgresql_where=sa.text("status = 'processing'"),
    )
    op.drop_index(
        "ix_schedule_runs_pending_due",
        table_name="schedule_runs",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("schedule_runs")
    op.drop_index("ix_operation_logs_schedule_created_desc", table_name="operation_logs")
    op.drop_index("ix_operation_logs_actor_created_desc", table_name="operation_logs")
    op.drop_table("operation_logs")
    op.drop_index("ix_schedules_status_terminal_at", table_name="schedules")
    op.drop_index("ix_schedules_guild_status_next_run", table_name="schedules")
    op.drop_index("ix_schedules_creator_status_next_run", table_name="schedules")
    op.drop_table("schedules")
    # ### end Alembic commands ###
